import * as XLSX from 'xlsx';
import PDFDocument from 'pdfkit';
import { ExportDataPayload } from '../types/report.types.js';

/**
 * Generates an Excel (.xlsx) file buffer from report data
 */
export const generateExcelBuffer = (payload: ExportDataPayload): Buffer => {
  const wb = XLSX.utils.book_new();

  // 1. Build Title & Metadata Rows
  const sheetRows: any[][] = [];
  sheetRows.push([payload.institutionName.toUpperCase()]);
  sheetRows.push([payload.reportTitle]);
  sheetRows.push([`Generated On: ${payload.reportDate} | Generated By: ${payload.generatedBy}`]);

  // Filters
  const filterEntries = Object.entries(payload.appliedFilters)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${k}: ${v}`);
  if (filterEntries.length > 0) {
    sheetRows.push([`Filters: ${filterEntries.join(' | ')}`]);
  } else {
    sheetRows.push(['Filters: None (All Data)']);
  }

  // Summary Metrics (if available)
  if (payload.summaryMetrics && Object.keys(payload.summaryMetrics).length > 0) {
    sheetRows.push([]);
    sheetRows.push(['SUMMARY METRICS']);
    Object.entries(payload.summaryMetrics).forEach(([k, v]) => {
      sheetRows.push([k, v]);
    });
  }

  sheetRows.push([]); // Empty spacer row

  // Data Table Headers
  const headers = payload.columns.map((col) => col.header);
  sheetRows.push(headers);

  // Data Rows
  payload.data.forEach((item) => {
    const row = payload.columns.map((col) => {
      const val = item[col.key];
      if (val === undefined || val === null) return '';
      if (typeof val === 'boolean') return val ? 'YES' : 'NO';
      if (typeof val === 'number') return val;
      return String(val);
    });
    sheetRows.push(row);
  });

  const ws = XLSX.utils.aoa_to_sheet(sheetRows);

  // Set column widths
  const colWidths = payload.columns.map((col) => ({
    wch: Math.max(col.header.length + 4, col.width || 15),
  }));
  ws['!cols'] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, 'Report_Data');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
};

/**
 * Generates an RFC-4180 CSV buffer from report data
 */
export const generateCsvBuffer = (payload: ExportDataPayload): Buffer => {
  const lines: string[] = [];

  // Metadata comments
  lines.push(`# ${payload.institutionName}`);
  lines.push(`# ${payload.reportTitle}`);
  lines.push(`# Generated: ${payload.reportDate} by ${payload.generatedBy}`);

  const filterEntries = Object.entries(payload.appliedFilters)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${k}=${v}`);
  if (filterEntries.length > 0) {
    lines.push(`# Filters: ${filterEntries.join(', ')}`);
  }

  if (payload.summaryMetrics) {
    const summaryStr = Object.entries(payload.summaryMetrics)
      .map(([k, v]) => `${k}: ${v}`)
      .join(' | ');
    lines.push(`# Summary: ${summaryStr}`);
  }

  lines.push(''); // blank line

  // Escape helper for CSV
  const escapeCsv = (val: any): string => {
    if (val === undefined || val === null) return '""';
    if (typeof val === 'boolean') return val ? '"YES"' : '"NO"';
    const str = String(val).replace(/"/g, '""');
    return `"${str}"`;
  };

  // Headers
  lines.push(payload.columns.map((c) => escapeCsv(c.header)).join(','));

  // Rows
  payload.data.forEach((item) => {
    const row = payload.columns.map((col) => escapeCsv(item[col.key]));
    lines.push(row.join(','));
  });

  // Include UTF-8 BOM so Excel opens CSV with proper encoding
  const csvContent = '\uFEFF' + lines.join('\r\n');
  return Buffer.from(csvContent, 'utf-8');
};

/**
 * Generates a PDF buffer using PDFKit with college branding and tabular format
 */
export const generatePdfBuffer = async (payload: ExportDataPayload): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const isLandscape = payload.columns.length > 5;
      const doc = new PDFDocument({
        size: 'A4',
        layout: isLandscape ? 'landscape' : 'portrait',
        margin: 36,
        bufferPages: true,
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      const pageWidth = isLandscape ? 841.89 : 595.28;
      const margin = 36;
      const usableWidth = pageWidth - margin * 2;

      // Header Banner
      doc.rect(margin, margin, usableWidth, 42).fill('#1e1b4b');
      doc
        .fillColor('#ffffff')
        .font('Helvetica-Bold')
        .fontSize(14)
        .text(payload.institutionName.toUpperCase(), margin + 12, margin + 8, {
          width: usableWidth - 24,
        });
      doc
        .fillColor('#a5b4fc')
        .font('Helvetica')
        .fontSize(9)
        .text(payload.reportTitle.toUpperCase(), margin + 12, margin + 26, {
          width: usableWidth - 24,
        });

      doc.y = margin + 50;

      // Metadata section
      doc.fillColor('#334155').font('Helvetica').fontSize(8);
      const metaText = `Generated: ${payload.reportDate} | By: ${payload.generatedBy}`;
      doc.text(metaText, margin, doc.y);

      const filterList = Object.entries(payload.appliedFilters)
        .filter(([, v]) => v !== undefined && v !== '')
        .map(([k, v]) => `${k}: ${v}`)
        .join(' | ');
      doc.text(`Applied Filters: ${filterList || 'All Records'}`, margin, doc.y + 2);
      doc.y += 12;

      // Summary Metrics Cards (if any)
      if (payload.summaryMetrics && Object.keys(payload.summaryMetrics).length > 0) {
        const metrics = Object.entries(payload.summaryMetrics);
        const cardWidth = Math.min(130, usableWidth / metrics.length - 8);
        let startX = margin;

        metrics.forEach(([k, v]) => {
          doc.rect(startX, doc.y, cardWidth, 32).fill('#f1f5f9');
          doc.rect(startX, doc.y, cardWidth, 32).stroke('#cbd5e1');
          doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(6).text(k.toUpperCase(), startX + 6, doc.y + 5, { width: cardWidth - 12 });
          doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(10).text(String(v), startX + 6, doc.y + 16, { width: cardWidth - 12 });
          startX += cardWidth + 8;
        });
        doc.y += 40;
      } else {
        doc.y += 6;
      }

      // Calculate column widths
      const totalRequestedWidth = payload.columns.reduce((sum, c) => sum + (c.width || 20), 0);
      const colWidths = payload.columns.map((c) => ((c.width || 20) / totalRequestedWidth) * usableWidth);

      // Render Table Header
      const renderTableHeader = (yPos: number) => {
        doc.rect(margin, yPos, usableWidth, 18).fill('#312e81');
        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(7);
        let currentX = margin;
        payload.columns.forEach((col, idx) => {
          doc.text(col.header.toUpperCase(), currentX + 4, yPos + 5, {
            width: colWidths[idx] - 8,
            ellipsis: true,
          });
          currentX += colWidths[idx];
        });
      };

      let currentY = doc.y;
      renderTableHeader(currentY);
      currentY += 18;

      const maxY = (isLandscape ? 595.28 : 841.89) - margin - 25;

      // Render Data Rows
      payload.data.forEach((row, rowIdx) => {
        if (currentY > maxY) {
          doc.addPage();
          currentY = margin;
          renderTableHeader(currentY);
          currentY += 18;
        }

        const bgColor = rowIdx % 2 === 0 ? '#ffffff' : '#f8fafc';
        doc.rect(margin, currentY, usableWidth, 16).fill(bgColor);
        doc.rect(margin, currentY, usableWidth, 16).stroke('#e2e8f0');

        doc.fillColor('#1e293b').font('Helvetica').fontSize(6.5);
        let currentX = margin;
        payload.columns.forEach((col, colIdx) => {
          const rawVal = row[col.key];
          let formattedVal = '';
          if (rawVal !== undefined && rawVal !== null) {
            if (typeof rawVal === 'boolean') {
              formattedVal = rawVal ? 'PASS' : 'FAIL';
            } else {
              formattedVal = String(rawVal);
            }
          }

          doc.text(formattedVal, currentX + 4, currentY + 4, {
            width: colWidths[colIdx] - 8,
            ellipsis: true,
          });
          currentX += colWidths[colIdx];
        });

        currentY += 16;
      });

      // Add Page Numbers in footer across all pages
      const range = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(i);
        const footerY = (isLandscape ? 595.28 : 841.89) - margin + 8;
        doc
          .fillColor('#94a3b8')
          .font('Helvetica')
          .fontSize(7)
          .text(
            `Page ${i + 1} of ${range.count} • Confidential Official Placement Report • Generated ${payload.reportDate}`,
            margin,
            footerY,
            { align: 'center', width: usableWidth }
          );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generates an official print-friendly standalone HTML document
 */
export const generateHtmlPrint = (payload: ExportDataPayload): string => {
  const filterSummary = Object.entries(payload.appliedFilters)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `<span class="badge badge-filter">${escapeHtml(k)}: ${escapeHtml(String(v))}</span>`)
    .join(' ');

  let summaryCardsHtml = '';
  if (payload.summaryMetrics && Object.keys(payload.summaryMetrics).length > 0) {
    summaryCardsHtml = `
      <div class="summary-grid">
        ${Object.entries(payload.summaryMetrics)
          .map(
            ([k, v]) => `
          <div class="summary-card">
            <div class="summary-label">${escapeHtml(k)}</div>
            <div class="summary-value">${escapeHtml(String(v))}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `;
  }

  const tableHeadersHtml = payload.columns
    .map((col) => `<th>${escapeHtml(col.header)}</th>`)
    .join('');

  const tableRowsHtml = payload.data
    .map((row, idx) => {
      const cells = payload.columns
        .map((col) => {
          const val = row[col.key];
          if (val === undefined || val === null) return '<td>-</td>';
          if (typeof val === 'boolean') {
            const cls = val ? 'badge-pass' : 'badge-fail';
            return `<td><span class="badge ${cls}">${val ? 'PASSED' : 'FAILED'}</span></td>`;
          }
          return `<td>${escapeHtml(String(val))}</td>`;
        })
        .join('');
      return `<tr class="${idx % 2 === 0 ? 'even' : 'odd'}">${cells}</tr>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(payload.reportTitle)} - Official Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #1e293b;
      background: #f8fafc;
      padding: 24px;
      font-size: 11px;
    }
    .print-bar {
      margin-bottom: 20px;
      display: flex;
      justify-content: flex-end;
      gap: 12px;
    }
    .btn {
      padding: 8px 16px;
      border-radius: 6px;
      border: 1px solid #cbd5e1;
      background: #ffffff;
      color: #334155;
      font-weight: 600;
      cursor: pointer;
      font-size: 12px;
    }
    .btn-primary {
      background: #4f46e5;
      color: #ffffff;
      border-color: #4338ca;
    }
    .report-container {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 24px;
      box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
    }
    .header-banner {
      border-bottom: 2px solid #4f46e5;
      padding-bottom: 14px;
      margin-bottom: 16px;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    .institution-name {
      font-size: 16px;
      font-weight: 800;
      color: #1e1b4b;
      letter-spacing: 0.5px;
    }
    .report-title {
      font-size: 13px;
      font-weight: 600;
      color: #4f46e5;
      margin-top: 4px;
    }
    .meta-box {
      text-align: right;
      font-size: 10px;
      color: #64748b;
      line-height: 1.5;
    }
    .filters-section {
      background: #f1f5f9;
      padding: 10px 14px;
      border-radius: 6px;
      margin-bottom: 16px;
      font-size: 10px;
      color: #475569;
    }
    .badge {
      display: inline-block;
      padding: 2px 6px;
      border-radius: 4px;
      font-weight: 600;
      font-size: 9px;
    }
    .badge-filter { background: #e2e8f0; color: #334155; margin-right: 4px; }
    .badge-pass { background: #dcfce7; color: #166534; }
    .badge-fail { background: #fee2e2; color: #991b1b; }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
      gap: 12px;
      margin-bottom: 20px;
    }
    .summary-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 6px;
      padding: 10px;
      border-left: 3px solid #4f46e5;
    }
    .summary-label {
      font-size: 9px;
      color: #64748b;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .summary-value {
      font-size: 14px;
      font-weight: 700;
      color: #0f172a;
      margin-top: 4px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }
    th {
      background: #1e1b4b;
      color: #ffffff;
      font-weight: 700;
      text-align: left;
      padding: 8px 10px;
      font-size: 9.5px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    td {
      padding: 7px 10px;
      border-bottom: 1px solid #e2e8f0;
      font-size: 10px;
    }
    tr.odd { background: #f8fafc; }
    tr.even { background: #ffffff; }
    .footer-note {
      margin-top: 24px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 9px;
      color: #94a3b8;
    }
    @media print {
      body { background: #ffffff; padding: 0; }
      .print-bar { display: none !important; }
      .report-container { border: none; box-shadow: none; padding: 0; }
      th { background: #1e1b4b !important; color: #ffffff !important; -webkit-print-color-adjust: exact; }
      .summary-card { -webkit-print-color-adjust: exact; }
      tr.odd { background: #f8fafc !important; -webkit-print-color-adjust: exact; }
      @page {
        size: A4 landscape;
        margin: 12mm;
      }
    }
  </style>
</head>
<body>
  <div class="print-bar">
    <button class="btn btn-primary" onclick="window.print()">Print Document</button>
    <button class="btn" onclick="window.close()">Close</button>
  </div>
  <div class="report-container">
    <div class="header-banner">
      <div>
        <div class="institution-name">${escapeHtml(payload.institutionName)}</div>
        <div class="report-title">${escapeHtml(payload.reportTitle)}</div>
      </div>
      <div class="meta-box">
        <div><strong>Date:</strong> ${escapeHtml(payload.reportDate)}</div>
        <div><strong>Generated By:</strong> ${escapeHtml(payload.generatedBy)}</div>
        <div><strong>Total Records:</strong> ${payload.data.length}</div>
      </div>
    </div>

    <div class="filters-section">
      <strong>Active Filter Parameters:</strong> ${filterSummary || 'All Academic Records'}
    </div>

    ${summaryCardsHtml}

    <table>
      <thead>
        <tr>${tableHeadersHtml}</tr>
      </thead>
      <tbody>
        ${tableRowsHtml}
      </tbody>
    </table>

    <div class="footer-note">
      <div>Official Verification Document • Placement & Assessment Directorate</div>
      <div>Generated Timestamp: ${escapeHtml(payload.reportDate)}</div>
    </div>
  </div>
</body>
</html>`;
};

const escapeHtml = (unsafe: string): string => {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
};
